[project]
name = "04-agent-as-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.14.1",
    "strands-agents[a2a]>=1.9.0",
    "strands-agents-tools[a2a-client]>=0.2.8",
    "uvicorn>=0.35.0",
]
